# Generated by Django 5.0.3 on 2024-11-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0010_learningplan_methodist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningplan',
            old_name='methodist',
            new_name='metodist',
        ),
    ]
