# Generated by Django 5.0.3 on 2024-12-23 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0013_alter_learningplan_curators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='curators',
            field=models.ManyToManyField(related_name='plan_curator', to=settings.AUTH_USER_MODEL, verbose_name='Кураторы'),
        ),
    ]
