# Generated by Django 5.0.3 on 2025-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0015_learningplan_pre_hw_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='can_report_lesson_name_only',
            field=models.BooleanField(default=False, verbose_name='Заполнять только наименование занятия'),
        ),
    ]
