# Generated by Django 5.0.3 on 2025-09-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0017_learningplan_admin_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='admin_comment_last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение комментария администратора'),
        ),
        migrations.CreateModel(
            name='LearningPlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Обратная связь')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.AddField(
            model_name='learningplan',
            name='feedbacks',
            field=models.ManyToManyField(to='learning_plan.learningplanfeedback', verbose_name='Обратные связи'),
        ),
    ]
