# Generated by Django 5.0.3 on 2025-03-13 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMailingTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.JSONField(default=list, verbose_name='Пользователи')),
                ('messages', models.JSONField(default=list, verbose_name='Информация о сообщениях')),
                ('result_info', models.JSONField(default=list, verbose_name='Подробный резульатат')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
        ),
    ]
