# Generated by Django 5.0.3 on 2025-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmailingtasks',
            name='users',
            field=models.JSONField(default=dict, verbose_name='Пользователи'),
        ),
    ]
