# Generated by Django 5.0.3 on 2025-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_groupmailingtasks_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmailingtasks',
            name='name',
            field=models.CharField(default='Рассылка', max_length=200, verbose_name='Наименование рассылки'),
            preserve_default=False,
        ),
    ]
