# Generated by Django 5.0.3 on 2024-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('path', models.FileField(unique=True, upload_to='files/', verbose_name='Путь')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('last_used_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее использование')),
                ('tg_url', models.CharField(blank=True, null=True, verbose_name='ID файла в Telegram')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('last_used_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее использование')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Общие материалы'), (2, 'Индивидуальные материалы')], default=2, verbose_name='Тип')),
                ('moderated', models.BooleanField(blank=True, null=True, verbose_name='Отмодерированный')),
                ('visible', models.BooleanField(blank=True, default=True, verbose_name='Видимость материала')),
                ('tg_url', models.CharField(blank=True, null=True, verbose_name='ID файла в Telegram')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория материалов',
                'verbose_name_plural': 'Категории материалов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
            ],
        ),
    ]
