# Generated by Django 5.0.3 on 2024-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(max_length=500, upload_to='materials/', verbose_name='Файл'),
        ),
    ]
