# Generated by Django 5.0.3 on 2024-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подпись'),
        ),
    ]
