# Generated by Django 5.0.3 on 2025-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_animation',
            field=models.BooleanField(default=False, verbose_name='Является анимацией'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_animation',
            field=models.BooleanField(default=False, verbose_name='Является анимацией'),
        ),
    ]
