# Generated by Django 5.0.3 on 2025-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_material_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, null=True, verbose_name='Расширение файла'),
        ),
    ]
