volumes:
  forschools_dev_pgdata:
  forschools_dev_redisdata:

services:
  forschools_dev_database:
    image: postgres:latest
    ports:
      - "${DB_PORT_FORWARD}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
    volumes:
      - forschools_dev_pgdata:/var/lib/postgresql/data
    restart: always

  forschools_dev_redis:
    ports:
      - "6379:6379"
    image: redis:latest
    restart: always
    volumes:
      - forschools_dev_redisdata:/data

  forschools_dev_local_tg_server:
    build:
      context: telegram_local_server
      args:
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8083:8083"
    volumes:
      - ${TELEGRAM_FILES_PATH}:/src/tgdata
    entrypoint: bash -c  "telegram-bot-api --api-id=${TELEGRAM_API_ID} --api-hash=${TELEGRAM_API_HASH} --http-ip-address=0.0.0.0 --http-port=8083 --dir=/src";
    restart: always