volumes:
  devserver_pgdata:
  devserver_redisdata:

services:
  devserver_database:
    image: postgres:latest
    ports:
      - "${DB_PORT_FORWARD}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
    volumes:
      - devserver_pgdata:/var/lib/postgresql/data
    restart: always

  devserver_django:
    build: .
    ports:
      - "${GUNICORN_PORT}:5000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TG_WEBHOOKS_MODE: ${TG_WEBHOOKS_MODE}
      TG_WEB_SERVER_HOST: ${TG_WEB_SERVER_HOST}
      TG_WEB_SERVER_PORT: ${TG_WEB_SERVER_PORT}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      TG_WEBHOOK_PATH: ${TG_WEBHOOK_PATH}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      REDIS_HOST: ${REDIS_HOST}
      DB_PORT: ${DB_PORT}
      TGPARSER_SESSION_NAME: ${TGPARSER_SESSION_NAME}
      TGPARSER_API_ID: ${TGPARSER_API_ID}
      TGPARSER_API_HASH: ${TGPARSER_API_HASH}
      TGPARSER_CHANNEL_NAME: ${TGPARSER_CHANNEL_NAME}
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:5000 dls.wsgi:application";
    depends_on:
      - devserver_database
    volumes:
      - /home/sdo/devserver/media:/src/media
      - /home/sdo/static:/src/static
    restart: always

  devserver_redis:
    image: redis:latest
    restart: always
    volumes:
      - devserver_redisdata:/data

  devserver_celery:
    build: .
    depends_on:
      - devserver_redis
      - devserver_django
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TG_WEBHOOKS_MODE: ${TG_WEBHOOKS_MODE}
      TG_WEB_SERVER_HOST: ${TG_WEB_SERVER_HOST}
      TG_WEB_SERVER_PORT: ${TG_WEB_SERVER_PORT}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      TG_WEBHOOK_PATH: ${TG_WEBHOOK_PATH}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    command: celery -A dls worker -l info

  devserver_celerybeat:
    build: .
    depends_on:
      - devserver_redis
      - devserver_django
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TG_WEBHOOKS_MODE: ${TG_WEBHOOKS_MODE}
      TG_WEB_SERVER_HOST: ${TG_WEB_SERVER_HOST}
      TG_WEB_SERVER_PORT: ${TG_WEB_SERVER_PORT}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      TG_WEBHOOK_PATH: ${TG_WEBHOOK_PATH}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    command: celery -A dls beat -l info

  devserver_bot:
    build: .
    ports:
      - "${TG_WEB_SERVER_PORT}:8080"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TG_WEBHOOKS_MODE: ${TG_WEBHOOKS_MODE}
      TG_WEB_SERVER_HOST: ${TG_WEB_SERVER_HOST}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      TG_WEBHOOK_PATH: ${TG_WEBHOOK_PATH}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py runbot";
    volumes:
      - /home/sdo/devserver/media:/src/media
    depends_on:
      - devserver_celery
      - devserver_redis
    restart: always