# Generated by Django 5.0.3 on 2024-04-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgramHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('materials', models.ManyToManyField(blank=True, related_name='learning_program_homework', to='material.material', verbose_name='Материалы')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgramLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание урока')),
                ('homeworks', models.ManyToManyField(blank=True, to='learning_program.learningprogramhomework', verbose_name='Домашние задания')),
                ('materials', models.ManyToManyField(blank=True, related_name='learning_program_lesson', to='material.material', verbose_name='Материалы')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgramPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('purpose', models.CharField(blank=True, null=True, verbose_name='Цель')),
                ('lessons', models.ManyToManyField(blank=True, to='learning_program.learningprogramlesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Этап программы обучения',
                'verbose_name_plural': 'Этапы программы обучения',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('purpose', models.CharField(blank=True, null=True, verbose_name='Цель')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('phases', models.ManyToManyField(blank=True, to='learning_program.learningprogramphase', verbose_name='Этапы программы обучения')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['pk'],
            },
        ),
    ]
