# Generated by Django 5.0.3 on 2024-05-06 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogram',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='learningprogram',
            name='phases_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Порядок этапов'),
        ),
        migrations.AddField(
            model_name='learningprogram',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, verbose_name='Видимость программы'),
        ),
        migrations.AddField(
            model_name='learningprogramhomework',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='learningprogramhomework',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, verbose_name='Видимость ДЗ'),
        ),
        migrations.AddField(
            model_name='learningprogramlesson',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='learningprogramlesson',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, verbose_name='Видимость урока'),
        ),
        migrations.AddField(
            model_name='learningprogramphase',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='learningprogramphase',
            name='lessons_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Порядок уроков'),
        ),
        migrations.AddField(
            model_name='learningprogramphase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='learningprogramphase',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, verbose_name='Видимость этапа'),
        ),
        migrations.AlterField(
            model_name='learningprogram',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
