# Generated by Django 5.0.3 on 2024-06-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_program', '0002_learningprogram_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogramhomework',
            name='materials_comment',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Описание материала'),
        ),
    ]
