# Generated by Django 5.0.3 on 2025-03-14 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_groupmailingtasks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmailingtasks',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время рассылки'),
            preserve_default=False,
        ),
    ]
