# Generated by Django 5.0.3 on 2024-10-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WSGIErrorsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ошибки')),
                ('exception', models.TextField(null=True, verbose_name='Ошибка')),
                ('path_info', models.CharField(verbose_name='Путь')),
                ('method', models.CharField(verbose_name='Метод')),
                ('status_code', models.IntegerField(verbose_name='Статус ответа')),
                ('params', models.JSONField(default={}, verbose_name='Параметры запроса')),
                ('handling_status', models.IntegerField(default=0, verbose_name='Статус обработки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
