# Generated by Django 5.0.3 on 2024-10-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_wsgierrorslog_handling_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='supportticketanswers',
            name='comment',
            field=models.TextField(max_length=3000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='supportticketanswers',
            name='read_by',
            field=models.ManyToManyField(related_name='ticketsanswers_read_by', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='supportticketanswers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticketsanswers_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
