# Generated by Django 5.0.3 on 2025-01-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0015_delete_userlog'),
        ('support', '0006_wsgierrorslog_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramErrorsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(choices=[(0, 'Сообщение'), (1, 'Callback')], default=0, verbose_name='Тип события')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('error', models.TextField(null=True, verbose_name='Ошибка')),
                ('traceback_log', models.JSONField(default=list, verbose_name='Трейсбэк')),
                ('params', models.JSONField(default=dict, verbose_name='Параметры запроса')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ошибки')),
                ('handling_status', models.IntegerField(choices=[(0, 'Новая ошибка'), (1, 'В работе'), (2, 'Ошибка исправлена')], default=0, verbose_name='Статус обработки')),
                ('tg_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_management.telegram', verbose_name='Запись Telegram')),
            ],
        ),
    ]
