# Generated by Django 5.0.3 on 2025-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_telegramerrorslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramerrorslog',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'Сообщение'), (1, 'Callback'), (2, 'Добавление материала')], default=0, verbose_name='Тип события'),
        ),
    ]
