# Generated by Django 5.0.1 on 2024-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последняя активность'),
        ),
    ]
