# Generated by Django 5.0.1 on 2024-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_remove_newuser_role_alter_newuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='tg_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код для присоединения Telegram'),
        ),
    ]
