# Generated by Django 5.0.3 on 2024-08-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0003_telegram_notifications_changed_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Город')),
                ('tz', models.IntegerField(default=0, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='programs',
        ),
        migrations.AddField(
            model_name='newuser',
            name='patronymic',
            field=models.CharField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_management.cities', verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
