# Generated by Django 5.0.3 on 2024-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0005_alter_newuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='last_message_from_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID последнего сообщения от пользователя'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='last_message_from_user_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего взаимодействия с ботом'),
        ),
    ]
