# Generated by Django 5.0.3 on 2024-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0006_telegram_last_message_from_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='progress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='work_experience',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Опыт работы'),
        ),
    ]
