# Generated by Django 5.0.3 on 2024-10-08 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0007_alter_newuser_note_alter_newuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='parents',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Родители'),
        ),
    ]
