# Generated by Django 5.0.3 on 2024-10-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0008_newuser_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='usertype',
            field=models.CharField(default='main', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
