# Generated by Django 5.0.3 on 2025-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0018_alter_profileeventsjournal_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='notifications_changed_lesson',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='notifications_lesson_day',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='notifications_lessons_hour',
        ),
        migrations.AddField(
            model_name='telegram',
            name='setting_notifications_lesson_day',
            field=models.BooleanField(default=True, verbose_name='НАСТРОЙКА: Уведомление о занятии за сутки'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='setting_notifications_lessons_hour',
            field=models.BooleanField(default=True, verbose_name='НАСТРОЙКА: Уведомление о занятии за час'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='setting_notifications_tg_connecting',
            field=models.BooleanField(default=True, verbose_name='НАСТРОЙКА: Уведомление о привязке пользователя к TG'),
        ),
    ]
