# Generated by Django 5.0.3 on 2025-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0021_telegram_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='city',
        ),
        migrations.AddField(
            model_name='newuser',
            name='tz',
            field=models.IntegerField(default=3, verbose_name='Часовой пояс'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
