# Generated by Django 5.0.3 on 2025-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0022_remove_newuser_city_newuser_tz_delete_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='setting_lesson_review_form_mode',
            field=models.IntegerField(choices=[(0, 'Telegram WebApp'), (1, 'Telegram Chat')], default=0, verbose_name='НАСТРОЙКА: Режим заполнения формы'),
        ),
    ]
