# Generated by Django 5.0.3 on 2025-05-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0024_telegram_allowed_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='access_token',
            field=models.CharField(blank=True, null=True, verbose_name='Токен авторизации'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='access_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения токена'),
        ),
    ]
