# Generated by Django 5.0.3 on 2024-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupchats'),
        ('profile_management', '0012_alter_telegram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchats',
            name='users_tg',
            field=models.ManyToManyField(related_name='group_chats', to='profile_management.telegram', verbose_name='Пользователи TG'),
        ),
    ]
