# Generated by Django 5.0.3 on 2025-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_receiver_tg_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.JSONField(default=list, null=True, verbose_name='Тэги'),
        ),
    ]
