# Generated by Django 5.0.3 on 2025-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_type',
            field=models.IntegerField(choices=[(0, 'Основной'), (1, 'Родительский')], default=0, verbose_name='Тип профиля получателя'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.IntegerField(choices=[(0, 'Основной'), (1, 'Родительский')], default=0, verbose_name='Тип профиля отправителя'),
        ),
    ]
