# Generated by Django 5.0.3 on 2025-02-18 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateFilesTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Все планы обучения')], verbose_name='Тип задания')),
                ('task_dt', models.DateField(auto_now_add=True, verbose_name='Дата и время задания')),
                ('task_complete', models.DateField(blank=True, null=True, verbose_name='Дата и время выполнения')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Готовый файл')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Задание на генерацию',
                'verbose_name_plural': 'Задания на генерацию',
                'ordering': ['-task_dt'],
            },
        ),
    ]
