# Generated by Django 5.0.3 on 2025-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_data', '0002_alter_generatefilestasks_task_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatefilestasks',
            name='type',
            field=models.IntegerField(choices=[(1, 'Все планы обучения'), (2, 'Занятия')], verbose_name='Тип задания'),
        ),
    ]
