# Generated by Django 5.0.3 on 2024-08-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_tgbotjournal_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgbotjournal',
            name='error',
        ),
    ]
