# Generated by Django 5.0.3 on 2025-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0002_alter_userlog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='buttons',
            field=models.JSONField(default=list, verbose_name='Кнопки'),
        ),
    ]
