# Generated by Django 5.0.3 on 2025-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0007_userlog_files_alter_userlog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Работа методиста'), (2, 'Занятие'), (3, 'Учебный план'), (4, 'Домашнее задание'), (5, 'Комментарий администратора на занятие')], default=0, verbose_name='Тип события'),
        ),
    ]
