# Generated by Django 5.0.3 on 2025-04-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_file_extension'),
        ('user_logs', '0008_alter_userlog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='files_db',
            field=models.ManyToManyField(related_name='user_logs_files', to='material.file'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='materials_db',
            field=models.ManyToManyField(related_name='user_logs_materials', to='material.material'),
        ),
    ]
