# Generated by Django 5.0.3 on 2024-10-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_file_caption'),
        ('support', '0003_wsgierrorslog_traceback_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsgierrorslog',
            name='handling_status',
            field=models.IntegerField(choices=[(0, 'Новая ошибка'), (1, 'В работе'), (2, 'Ошибка исправлена')], default=0, verbose_name='Статус обработки'),
        ),
        migrations.CreateModel(
            name='SupportTicketAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(0, 'Новая ошибка'), (1, 'В работе'), (2, 'Ошибка исправлена')], default=0, verbose_name='Статус')),
                ('read_by', models.ManyToManyField(related_name='tickets_read_by', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_info', models.CharField(null=True, verbose_name='Путь')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('attachments', models.ManyToManyField(to='material.file', verbose_name='Файлы')),
                ('answers', models.ManyToManyField(to='support.supportticketanswers', verbose_name='Ответы')),
            ],
        ),
    ]
