# Generated by Django 5.0.3 on 2024-12-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_supportticket_user_alter_supportticket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsgierrorslog',
            name='response',
            field=models.JSONField(null=True, verbose_name='Ответ сервера'),
        ),
    ]
