# Generated by Django 5.0.1 on 2024-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='homework', related_query_name='homework_set', to='material.file', verbose_name='Файлы'),
        ),
    ]
