# Generated by Django 5.0.3 on 2024-04-19 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 20, 13, 4, 21, 460182), null=True, verbose_name='Срок'),
        ),
    ]
