# Generated by Django 5.0.1 on 2024-01-31 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 17, 49, 24, 121150), verbose_name='Срок'),
        ),
    ]
