# Generated by Django 5.0.3 on 2024-04-30 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-id'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домишние задания'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 1, 18, 47, 45, 910711), null=True, verbose_name='Срок'),
        ),
    ]
