# Generated by Django 5.0.1 on 2024-02-03 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 6, 45, 29, 272187), verbose_name='Срок'),
        ),
    ]
