# Generated by Django 5.0.3 on 2024-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_homework_for_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='for_curator',
            field=models.BooleanField(blank=True, default=True, verbose_name='Куратор работает с ДЗ'),
        ),
    ]
