# Generated by Django 5.0.3 on 2025-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_alter_homeworklog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий администратора'),
        ),
    ]
