# Generated by Django 5.0.3 on 2024-04-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', related_query_name='file_set', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='material',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='material_access', to=settings.AUTH_USER_MODEL, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='material',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='material', related_query_name='material_set', to='material.materialcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='material_level', to='material.materiallevel'),
        ),
    ]
