# Generated by Django 5.0.3 on 2025-03-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_file_is_animation_material_is_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='extension',
            field=models.CharField(blank=True, null=True, verbose_name='Расширение файла'),
        ),
    ]
