# Generated by Django 5.0.3 on 2024-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_alter_newuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='notifications_changed_lesson',
            field=models.BooleanField(default=True, verbose_name='Уведомление об изменении занятия'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='notifications_lesson_day',
            field=models.BooleanField(default=True, verbose_name='Уведомление о занятии за сутки'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='notifications_lessons_hour',
            field=models.BooleanField(default=True, verbose_name='Уведомление о занятии за час'),
        ),
    ]
