# Generated by Django 5.0.3 on 2024-09-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0004_cities_remove_newuser_programs_newuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ['-is_active', 'first_name', 'last_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
