# Generated by Django 5.0.3 on 2024-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0010_telegram_join_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='first_name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='last_name',
            field=models.CharField(blank=True, null=True, verbose_name='Фамилия'),
        ),
    ]
