# Generated by Django 5.0.3 on 2024-10-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0011_telegram_first_name_telegram_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram',
            options={'ordering': ['join_dt'], 'verbose_name': 'Привязанный Telegram', 'verbose_name_plural': 'Привязанные Telegram'},
        ),
    ]
