# Generated by Django 5.0.3 on 2024-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0012_alter_telegram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='setting_show_hw_materials',
            field=models.BooleanField(default=False, verbose_name='НАСТРОЙКА: Показывать материалы ДЗ'),
        ),
    ]
