# Generated by Django 5.0.3 on 2024-11-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0013_telegram_setting_show_hw_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='setting_show_hw_materials',
            field=models.BooleanField(default=True, verbose_name='НАСТРОЙКА: Показывать материалы ДЗ'),
        ),
    ]
