# Generated by Django 5.0.3 on 2025-01-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0014_alter_telegram_setting_show_hw_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
