# Generated by Django 5.0.3 on 2025-02-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0015_delete_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='parents',
        ),
    ]
