# Generated by Django 5.0.3 on 2025-03-06 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0016_remove_newuser_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEventsJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(0, 'Привязка Telegram'), (1, 'Отвязка Telegram')], verbose_name='Тип события')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_initiator', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие пользователя',
                'verbose_name_plural': 'События пользователя',
                'ordering': ['-dt'],
            },
        ),
    ]
