# Generated by Django 5.0.3 on 2025-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0017_profileeventsjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileeventsjournal',
            name='event',
            field=models.IntegerField(choices=[(0, 'Привязка основного Telegram'), (1, 'Привязка родительского Telegram'), (2, 'Отвязка основного Telegram'), (3, 'Отвязка родительского Telegram')], verbose_name='Тип события'),
        ),
    ]
