# Generated by Django 5.0.3 on 2025-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0019_remove_telegram_notifications_changed_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='setting_notifications_email',
            field=models.BooleanField(default=True, verbose_name='НАСТРОЙКА: Получать уведомления на email'),
        ),
    ]
