# Generated by Django 5.0.3 on 2025-04-07 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0020_newuser_setting_notifications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='allowed_users',
            field=models.ManyToManyField(related_name='telegram_allowed', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
