# Generated by Django 5.0.3 on 2025-05-16 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0023_telegram_setting_lesson_review_form_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='allowed_parents',
            field=models.ManyToManyField(related_name='telegram_allowed_parent', to=settings.AUTH_USER_MODEL, verbose_name='Авторизованный родитель'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='allowed_users',
            field=models.ManyToManyField(related_name='telegram_allowed_user', to=settings.AUTH_USER_MODEL, verbose_name='Авторизованный пользователь'),
        ),
    ]
