# Generated by Django 5.0.3 on 2025-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0025_telegram_access_token_telegram_access_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_activity_type',
            field=models.IntegerField(choices=[(0, 'Telegram бот'), (1, 'Web-браузер'), (2, 'Регистрация')], default=2, verbose_name='Тип последней активности'),
        ),
    ]
