# Generated by Django 5.0.3 on 2025-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0026_newuser_last_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='registration_url',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка для регистрации'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='registration_url_access',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
