# Generated by Django 5.0.3 on 2024-10-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver_tg_message_sender_tg_and_more'),
        ('profile_management', '0012_alter_telegram_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_tg_receiver', to='profile_management.telegram', verbose_name='Получатель TG'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_tg_sender', to='profile_management.telegram', verbose_name='Отправитель TG'),
        ),
    ]
