# Generated by Django 5.0.3 on 2025-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tags',
            field=models.JSONField(default=list, verbose_name='Тэги'),
        ),
    ]
