# Generated by Django 5.0.3 on 2025-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_receiver_type_message_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_tg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_tg',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_type',
            field=models.IntegerField(choices=[(0, 'Основной'), (1, 'Родительский'), (2, 'Администратор')], default=0, verbose_name='Тип профиля получателя'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.IntegerField(choices=[(0, 'Основной'), (1, 'Родительский'), (2, 'Администратор')], default=0, verbose_name='Тип профиля отправителя'),
        ),
    ]
