# Generated by Django 5.0.3 on 2024-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Место проведения занятия', 'verbose_name_plural': 'Места проведения занятий'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Не проведён'), (1, 'Проведён'), (2, 'Отменён')], default=0, verbose_name='Статус'),
        ),
    ]
