# Generated by Django 5.0.3 on 2024-07-24 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lesson_from_program_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='replace_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replace_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Замещающий преподаватель'),
        ),
    ]
