# Generated by Django 5.0.3 on 2025-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_place_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='conf_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Идентификатор конференции'),
        ),
    ]
