# Generated by Django 5.0.1 on 2024-01-30 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='Начало урока')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='Окончание урока')),
                ('zoom_url', models.URLField(default='https://', verbose_name='Ссылка Zoom')),
                ('evaluation', models.IntegerField(blank=True, null=True, verbose_name='Оценка урока')),
                ('note_teacher', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заметка преподавателя')),
                ('note_listener', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заметка ученика')),
                ('completed', models.BooleanField(default=False, verbose_name='Урок проведён')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', related_query_name='lesson_set', to='homework.homework', verbose_name='Домашнее задание')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['start'],
            },
        ),
    ]
