# Generated by Django 5.0.3 on 2024-04-16 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало занятия')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание занятия')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата занятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание занятия')),
                ('materials_access', models.BooleanField(blank=True, default=False, verbose_name='Видимость материалов')),
                ('evaluation', models.IntegerField(blank=True, null=True, verbose_name='Оценка занятия')),
                ('note_teacher', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заметка преподавателя')),
                ('note_listener', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заметка ученика')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Не проведён'), (1, 'Проведён')], default=0, verbose_name='Статус')),
                ('homeworks', models.ManyToManyField(blank=True, to='homework.homework', verbose_name='Домашние задания')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['date', 'pk'],
            },
        ),
    ]
