# Generated by Django 5.0.3 on 2024-04-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time', 'pk'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
