# Generated by Django 5.0.3 on 2024-12-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_lessonteacherreview_remove_lesson_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonteacherreview',
            old_name='used_materials',
            new_name='materials',
        ),
    ]
