# Generated by Django 5.0.3 on 2025-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_rename_used_materials_lessonteacherreview_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonteacherreview',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время заполнения'),
        ),
    ]
