# Generated by Django 5.0.3 on 2025-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_lessonteacherreview_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='access_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код доступа'),
        ),
    ]
