# Generated by Django 5.0.3 on 2025-01-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_place_conf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий администратора'),
        ),
    ]
