# Generated by Django 5.0.3 on 2025-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_lesson_additional_listeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name_fact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование фактическое'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование по плану'),
        ),
    ]
