# Generated by Django 5.0.3 on 2024-04-16 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, default=datetime.datetime(2024, 4, 17, 18, 57, 56, 582440), null=True, verbose_name='Срок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домишние задания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(1, 'Создано'), (2, 'Открыто'), (3, 'На проверке'), (4, 'Принято'), (5, 'На доработке'), (6, 'Отменено')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лог ДЗ',
                'verbose_name_plural': ('Логи ДЗ',),
                'ordering': ['-dt'],
            },
        ),
    ]
