# Generated by Django 5.0.3 on 2024-04-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='homework',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='homework', related_query_name='homework_set', to='material.material', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='homeworklog',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='hw_log', related_query_name='hw_log_set', to='material.file', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='homeworklog',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', related_query_name='log_set', to='homework.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='homeworklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_log', related_query_name='hw_log_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
