# Generated by Django 5.0.3 on 2024-04-23 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 24, 16, 33, 24, 349871), null=True, verbose_name='Срок'),
        ),
    ]
