# Generated by Django 5.0.3 on 2024-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_homework_deadline'),
        ('learning_program', '0003_learningprogramhomework_materials_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='from_programs_hw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_program.learningprogramhomework', verbose_name='Шаблон домашнего задания'),
        ),
    ]
