# Generated by Django 5.0.3 on 2024-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_homework_options_alter_homeworklog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworklog',
            name='agreement',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Согласование'),
        ),
    ]
