# Generated by Django 5.0.3 on 2024-11-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_homeworklog_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='for_curator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Куратор работает с ДЗ'),
        ),
    ]
