# Generated by Django 5.0.3 on 2025-02-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_homeworkgroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworklog',
            options={'ordering': ['-dt'], 'verbose_name': 'Лог ДЗ', 'verbose_name_plural': 'Логи ДЗ'},
        ),
    ]
