# Generated by Django 5.0.3 on 2025-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_homework_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
    ]
