# Generated by Django 5.0.3 on 2024-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('purpose', models.CharField(blank=True, null=True, verbose_name='Цель')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Обучение не начато'), (1, 'В процессе обучения'), (2, 'Обучение завершено'), (3, 'Обучение заморожено')], default=0, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('purpose', models.CharField(blank=True, null=True, verbose_name='Цель')),
                ('show_lessons', models.IntegerField(blank=True, null=True, verbose_name='Видимость уроков')),
                ('show_materials', models.IntegerField(blank=True, null=True, verbose_name='Видимость материалов')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Обучение не начато'), (1, 'В процессе обучения'), (2, 'Обучение завершено'), (3, 'Обучение заморожено')], default=0, verbose_name='Статус')),
            ],
        ),
    ]
