# Generated by Django 5.0.3 on 2024-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0004_learningplan_default_hw_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningphases',
            options={'ordering': ['pk'], 'verbose_name': 'Этап плана обучения', 'verbose_name_plural': 'Этапы плана обучения'},
        ),
        migrations.AlterModelOptions(
            name='learningplan',
            options={'ordering': ['pk'], 'verbose_name': 'План обучения', 'verbose_name_plural': 'Планы обучения'},
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='show_lessons',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='Видимость уроков'),
        ),
    ]
