# Generated by Django 5.0.3 on 2024-04-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0005_alter_learningphases_options_and_more'),
        ('learning_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='from_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_program.learningprogram', verbose_name='Из програмы:'),
        ),
    ]
