# Generated by Django 5.0.3 on 2024-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0007_learningplan_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningphases',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='learningphases',
            name='purpose',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Цель'),
        ),
    ]
