# Generated by Django 5.0.3 on 2024-11-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0009_alter_learningplan_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='methodist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_metodist', to=settings.AUTH_USER_MODEL, verbose_name='Методист'),
        ),
    ]
