# Generated by Django 5.0.3 on 2024-11-23 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0011_rename_methodist_learningplan_metodist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='curators',
            field=models.ManyToManyField(null=True, related_name='plan_cuarator', to=settings.AUTH_USER_MODEL, verbose_name='Кураторы'),
        ),
    ]
