# Generated by Django 5.0.3 on 2025-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0014_alter_learningplan_curators'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='pre_hw_comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий перед ДЗ'),
        ),
    ]
