# Generated by Django 5.0.3 on 2025-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0016_learningplan_can_report_lesson_name_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий администратора'),
        ),
    ]
