# Generated by Django 5.0.3 on 2025-01-08 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('content', models.JSONField(default={'list': [], 'text': []}, verbose_name='Контент')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('buttons', models.JSONField(default=[], verbose_name='Кнопки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
