# Generated by Django 5.0.3 on 2025-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0003_alter_userlog_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Работа методиста'), (2, 'Занятие')], default=0, verbose_name='Тип события'),
        ),
    ]
