# Generated by Django 5.0.3 on 2025-01-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0014_alter_learningplan_curators'),
        ('user_logs', '0004_userlog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='color',
            field=models.CharField(blank=True, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='learning_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_plan.learningplan', verbose_name='План обучения'),
        ),
    ]
