# Generated by Django 5.0.3 on 2025-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0006_alter_userlog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='files',
            field=models.JSONField(default=list, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Работа методиста'), (2, 'Занятие'), (3, 'Учебный план'), (4, 'Домашнее задание')], default=0, verbose_name='Тип события'),
        ),
    ]
