# Generated by Django 5.0.3 on 2024-08-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgBotJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(0, 'Другое'), (1, 'Расписание на завтра'), (2, 'Напоминание о занятии'), (3, 'Домашнее заданее: новое'), (4, 'Домашнее заданее: сдача/проверка'), (5, 'Материалы: ручная отправка'), (6, 'Материалы: автоматическая отправка')], default=0, verbose_name='Событие')),
                ('data', models.JSONField(default={dict}, verbose_name='Информация')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tgjournal_initiator', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tgjournal_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
        ),
    ]
