# Generated by Django 5.0.3 on 2024-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_tgbotjournal_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgbotjournal',
            options={'ordering': ['-dt'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домишние задания'},
        ),
        migrations.AddField(
            model_name='tgbotjournal',
            name='read',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения сообщения'),
        ),
        migrations.AlterField(
            model_name='tgbotjournal',
            name='event',
            field=models.IntegerField(choices=[(0, 'Другое'), (2, 'Напоминание о занятии'), (7, 'Новое сообщение')], default=0, verbose_name='Событие'),
        ),
    ]
