# Generated by Django 5.0.3 on 2024-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_tgbotjournal_options_tgbotjournal_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgbotjournal',
            name='event',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Расписание на завтра'), (2, 'Напоминание о занятии'), (3, 'Домашнее заданее: новое'), (4, 'Домашнее заданее: сдача/проверка'), (5, 'Материалы: ручная отправка'), (6, 'Материалы: автоматическая отправка'), (7, 'Новое сообщение')], default=0, verbose_name='Событие'),
        ),
    ]
