# Generated by Django 5.0.3 on 2024-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_tgbotjournal_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgbotjournal',
            name='read',
        ),
    ]
