# Generated by Django 5.0.3 on 2024-10-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_tgbotjournal_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgbotjournal',
            options={'ordering': ['-dt'], 'verbose_name': 'Запись Telegram', 'verbose_name_plural': 'Записи Telegram'},
        ),
    ]
