# Generated by Django 5.0.3 on 2025-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_alter_tgbotjournal_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgbotjournal',
            name='event',
            field=models.IntegerField(choices=[(0, 'Другое'), (1, 'Расписание на завтра'), (2, 'Напоминание о занятии'), (3, 'Домашнее заданее: новое'), (4, 'Домашнее заданее: сдача/проверка'), (5, 'Материалы: ручная отправка'), (6, 'Материалы: автоматическая отправка'), (7, 'Новое сообщение'), (8, 'Согласование ДЗ'), (9, 'Изменение ОС'), (10, 'Сообщения администратору'), (11, 'Привязка/отвязка Telegram'), (12, 'Напоминание о непроведённом занятии')], default=0, verbose_name='Событие'),
        ),
    ]
